<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>


	<FileVersion>1.0.0</FileVersion>
    <AssemblyVersion>1.0.0</AssemblyVersion>
    <Version>1.0.0</Version>
	
    <IsPackable>false</IsPackable>

    <RootNamespace>Aero.Cake</RootNamespace>

    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Extensions\**" />
    <Compile Remove="TestResults\**" />
    <EmbeddedResource Remove="Extensions\**" />
    <EmbeddedResource Remove="TestResults\**" />
    <None Remove="Extensions\**" />
    <None Remove="TestResults\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Cake.Frosting" />
    <PackageReference Include="Cake.Testing" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <DotNetCliToolReference Include="dotnet-xunit" Version="2.3.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Build\Aero.Build\Aero.Build.csproj" />
    <ProjectReference Include="..\Aero.Cake.TestSupport\Aero.Cake.TestSupport.csproj" />
    <ProjectReference Include="..\Aero.Cake\Aero.Cake.csproj" />
    <ProjectReference Include="..\Aero\Aero.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Features\DotNet\Services\TestFiles\ProjectFileWith1Framework.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Features\DotNet\Services\TestFiles\ProjectFileWith2Frameworks.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
